data_config:
  cand_pool_dir_name: cand_pool/local
  enable_query_instruct: true
  image_size: 224, 224
  query_instruct_path: instructions/query_instructions.tsv
  shuffle_cand: true
  test_dir_name: query/test
  train_dir_name: query/train
  val_dir_name: query/val
dataloader_config:
  batch_size: 24
  num_workers: 5
dist_config:
  dist_url: env://
embed_config:
  cand_pools_config:
    cand_pools_name_to_embed:
    - mscoco_task0_test
    - mscoco_task3_test
    - fashion200k_task3
    - nights_task4
    - fashioniq_task7
    - cirr_task7
    embed_union_pool: true
    enable_embed: true
  embed_dir_name: embed
  test_datasets_config:
    correspond_cand_pools_name:
    - mscoco_task0_test
    - mscoco_task3_test
    - fashion200k_task3
    - nights_task4
    - fashioniq_task7
    - cirr_task7
    datasets_name:
    - mscoco_task0
    - mscoco_task3
    - fashion200k_task3
    - nights_task4
    - fashioniq_task7
    - cirr_task7
    enable_embed: true
  train_datasets_config:
    correspond_cand_pools_name: null
    datasets_name: null
    enable_embed: false
  use_fp16: true
  val_datasets_config:
    correspond_cand_pools_name: null
    datasets_name: null
    enable_embed: false
experiment:
  description: ${model.name} ${model.size} ${experiment.instruct_status} ${experiment.exp_name}
  exp_name: InBatch
  instruct_status: Instruct
  path_suffix: ${model.short_name}/${model.size}/${experiment.instruct_status}/${experiment.exp_name}/
model:
  ckpt_config:
    ckpt_dir: checkpoint/${experiment.path_suffix}
    ckpt_name: clip_ff_large.pth
  clip_vision_model_name: ViT-L/14
  name: CLIPFeatureFusion
  pretrained_clip_model_dir: checkpoint/CLIP/
  short_name: CLIP_FF
  size: Large
seed: 2023
